version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram_reverseproxy
    image: reverseproxy
  backend_user:
    build:
      context: ./udagram_api_user
    image: udagram_user_api
  backend_feed:
    build:
      context: ./udagram_api_feed
    image: udagram_feed_api
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local