version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram_reverseproxy
    image: udacity_udagram_reverseproxy:v1.0.0
  backend_user:
    build:
      context: ./udagram_api_user
    image: udacity_udagram_api_user:v1.0.0
  backend_feed:
    build:
      context: ./udagram_api_feed
    image: udacity_udagram_api_feed:v1.0.0
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local